
# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "llvm-msvc-driver-template"
include-before = [
	"cmake/msvc-configurations.cmake",
]

[variables]
CMAKE_MODULE_PATH = "${CMAKE_CURRENT_SOURCE_DIR}/cmake"

[find-package.WDK]

[template.driver]
type = "executable"
add-function = "wdk_add_driver"
compile-features = ["cxx_std_20"]

[template.driver_lib]
type = "static"
add-function = "wdk_add_library"
compile-features = ["cxx_std_20"]


[target.utils]
type = "driver_lib"
sources = [
    "src/lib/utils/*.cpp",
    "src/lib/utils/*.h",
]

[target.drv1]
type = "driver"
sources = [
    "src/sys/drv1/*.cpp",
    "src/sys/drv1/*.h",
]
